---

- name: Install kind binary
  ansible.builtin.include_tasks:
    file: binary.yml

- name: Setup kind cluster
  ansible.builtin.include_tasks:
    file: cluster.yml
  when: lookup('env', 'MOLECULE_DRIVER_NAME') != 'docker' or ansible_os_family != 'Debian'

